version: '3.9'

services:
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=qwerty1234
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=devmetrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=gpntoken

# no volume 
