version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672     # Default RabbitMQ listener port
        - 15672:15672   # RabbitMQ management interface
    environment:
      RABBITMQ_DEFAULT_USER: "gpn"
      RABBITMQ_DEFAULT_PASS: "gpn"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq-logs:/var/log/rabbitmq

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local
